name: ci-pipeline
on:
  push:
    branches: ["main"]
#the actions are triggered on both pushing to main branch
  pull_request:           
    branches: ["main"]
#as well as to each pull requests made to the codebase
jobs:

# ---------------------------------------------------------
# CODE SECURITY (CodeQL) to generate CodeQL queries that look for patterns like-SQL injection,Command injection,XSS,Deserialization bugs,Hardcoded secrets,Insecure cryptography,Unsafe auth logic,Path traversal etc
# ---------------------------------------------------------
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Install Backend Deps
        working-directory: backend
        run: npm install

      - name: Install Frontend Deps
        working-directory: frontend
        run: npm install

      - name: Analyze
        uses: github/codeql-action/analyze@v3

# ---------------------------------------------------------
# LINT
# ---------------------------------------------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Backend Lint
        working-directory: backend
        run: |
          npm install
          npm run lint || echo "No backend lint"

      - name: Frontend Lint
        working-directory: frontend
        run: |
          npm install
          npm run lint || echo "No frontend lint"

# ---------------------------------------------------------
# TESTS
# ---------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Backend Tests
        working-directory: backend
        run: echo "No backend tests"

      - name: Frontend Tests
        working-directory: frontend
        run: echo "No frontend tests"

# ---------------------------------------------------------
# DOCKER BUILD + SECURITY + SBOM
# ---------------------------------------------------------
  secure-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      #  Trivy DB Cache (speed-up)
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}
          restore-keys: |
            trivy-db-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hardik0811
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Backend Docker image
        working-directory: backend
        run: docker build -t docker.io/hardik0811/educonnect-backend:latest .
      
      - name: Build Frontend Image
        working-directory: frontend
        run: docker build -t docker.io/hardik0811/educonnect-frontend:latest .

      # -------------------------------
      # Trivy vulnerability scan
      # -------------------------------
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0
        env:
          TRIVY_CACHE_DIR: ~/.cache/trivy
        with:
          image-ref: docker.io/hardik0811/educonnect-backend:latest
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          hide-progress: true
          exit-code: 0
      - name: Trivy Frontend Scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: docker.io/hardik0811/educonnect-frontend:latest
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          hide-progress: true
          exit-code: 0

      # -------------------------------
      # Generate SBOM (CycloneDX)
      # -------------------------------
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@0.24.0
        env:
          TRIVY_CACHE_DIR: ~/.cache/trivy
        with:
          image-ref: docker.io/hardik0811/educonnect-backend:latest
          format: cyclonedx
          output: sbom.json
          exit-code: 0


      #-------------------------------
      # Push Image
      # -------------------------------
      - name: Push Backend Image
        run: docker push docker.io/hardik0811/educonnect-backend:latest
      - name: Push Frontend Image
        run: docker push docker.io/hardik0811/educonnect-frontend:latest
